Homework 3. Dubrovchenko Mark
Mmorgenn/projects pull request #13
Opened 2023-10-09 18:13 UTC by Mmorgenn

2023-10-12 18:25 UTC, toadharvard requested changes

2023-10-12 18:25 UTC, toadharvard commented on src/homework/Homework 11.10.23/hw1.py
> +        print(f"Arity cannot be {arity}! Returned None")
Кривые входные данные? Exception!

2023-10-12 18:25 UTC, toadharvard commented on src/homework/Homework 11.10.23/hw1.py
> +def curry_explicit(function_name, arity: int):
Тебе не имя передается, а функция.

2023-10-12 18:25 UTC, toadharvard commented on src/homework/Homework 11.10.23/hw1.py
> +        return lambda: function_name()
return function

2023-10-12 18:25 UTC, toadharvard commented on src/homework/Homework 11.10.23/hw1.py
> +        print(f"Arity cannot be {arity}! Returned None")
Сюда тоже exception с нормальным собщением об ошибке.
Тут сейчас написана какая-то фигня. Мне что параметры перебирать, пока не узнаю, что арность должна быть < 0?

2023-10-12 18:25 UTC, toadharvard commented on src/homework/Homework 11.10.23/hw1.py
> +            print("Arity != the number of arguments! Returned None")
exception

2023-10-12 18:25 UTC, toadharvard commented on src/homework/Homework 11.10.23/hw1.py
> +            return function_name()
зачем функцию вызвал?
если суть в том, чтобы вернуть функцию, а не ее результат

2023-10-12 18:28 UTC, toadharvard commented
Названия коммитов кринж

2023-10-15 20:31 UTC, Mmorgenn commented on src/homework/Homework 11.10.23/hw1.py
> +            return function_name()
Не понимаю. В данном случаи не возвращается результат.

2023-10-16 20:43 UTC, toadharvard commented on src/homework/Homework 11.10.23/hw1.py
> +            return function_name()
> Не понимаю. В данном случаи не возвращается результат.

Ты прав, действительно результат ты возвращаешь только при вызове.

2023-10-17 19:41 UTC, toadharvard requested changes

2023-10-17 19:41 UTC, toadharvard commented on src/homework/Homework 11.10.23/hw1.py
> +        return None
```suggestion
        raise ValueError(f"{function} must be callable")
```

2023-10-17 19:41 UTC, toadharvard commented on src/homework/Homework 11.10.23/hw1.py
> +        print("Arity should be int > 0! Returned None")
Аналогично

2023-10-17 19:41 UTC, toadharvard commented on src/homework/Homework 11.10.23/hw1.py
> +        print(f"{function} is not function! Returned None")
Аналогично

2023-10-24 18:11 UTC, toadharvard approved these changes

2023-10-26 13:49 UTC, merged